version: '3'

services:
  postgres:
    container_name: api-cardapio
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api-cardapio
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata